#!/usr/bin/env bash
# Sets up a redirection on Nginx

# Exit on any error
set -e

# Update and install nginx if not installed
apt-get update
apt-get install -y nginx

# Create the custom redirect config file
REDIRECT_CONF="/etc/nginx/sites-available/default"

# Use sed to insert redirection configuration inside the default server block
sed -i '/^\s*location \/ {/i \
    location /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
    }\n' "$REDIRECT_CONF"

# Restart nginx to apply changes
systemctl restart nginx

